### ISSUE TITLE
Ocean Direct

### ISSUE THREAD

**Issue by natenouwels1** [gill14/AccuPatt#23]
Hi Matt, Is the Ocean Direct python module required to run the newest version of AccuPatt? Because it costs $625 and that's $625 more than I have to spend. It looks like the older versions will still work, but just wanted to make sure that we would still get the updates and bug fixes without Ocean Direct. Thanks very much!

**Comment by gill14** [comment]
The OceanDirect API will be included with future (>2.1.0) versions as a bundled dependency replacing python-seabreeze. There should be no purchase or action needed on the user's end. This change was required to support interchangeable use of legacy (USB2000+/Flame) and newer SR series spectrometers.
